# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qvrdfwIB0VGIjPlEwrpGpImk8Z_ED1ax
"""

import numpy as np
import pandas as pd

"""Question 1
Consider the vector [10, 11, 12, 13, 14], how to build a new vector with 5 consecutive zeros interleaved between each value?
"""

a=np.array([10,11,12,13,14],dtype='float')
print(a)

# after inserting zeroes between them 

b=np.zeros(len(a)+(len(a)-1)*5)
b[::6]=a
print("Output :")
print(b)

"""Question 2 Consider two random array A anb B, check if they are equal"""

from numpy import random

a=random.randint(2, size=(6))
print("a is ", a)

b=random.randint(2, size=(6))
print("b is ",b)

c=np.allclose(a,b) # element wise checking 

# If arrays are equal then c is true else false
print("Output :")
print(c)

"""Question 3 What is the result of the following expression ?"""

print("0 * np.nan : ",0 * np.nan)
print("np.nan != np.nan :",np.nan != np.nan)
print("np.inf > np.nan :",np.inf > np.nan)
print("np.nan - np.nan :",np.nan - np.nan)
print("0.3 == 3 * 0.1 :",0.3 == 3 * 0.1)

"""Question-4

Convert the first character of each element in a series to uppercase?
Sample Input
ser = pd.Series(['amrita', 'school', 'of', 'engineering' 'chennai' , 'campus'])
"""

ser=pd.Series(['amrita', 'school', 'of', 'engineering' , 'chennai' , 'campus'])
print(ser)

new=ser.str.capitalize()

print("output :")

for i in range(len(new)):
  print(new[i],end=" ")

"""Question-5

Do any two Exercises using Numpy

1.addition of 2 numpy arrays

3.Identity Matrix

"""

# Addition of 2 numpy array

a=np.array([[3,4,5],[1,1,1],[2,5,6]],dtype='int32')

b=np.array([[3,3,3],[1,5,1],[8,3,2]],dtype='int32')

print("Array A  is :")
print(a)

print("Array B  is :")
print(b)

print("Addition of A and B is :")
print(np.add(a,b))

# identity matrix using Numpy

i=np.identity(3,dtype='int32')
print("identity matrix is :")
print(i)