# -*- coding: utf-8 -*-
"""task6a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1El9EuhScYzjr45-GH2BwhlI-6KdIkJum
"""

lst=[]
with open('/content/onelinefile.txt','r') as rf:
  for line in rf:
    lst.extend(line.split())


  with open('/content/filename2.csv','w') as wf:
    for line in lst[::4]:
      wf.write(line)

