# -*- coding: utf-8 -*-
"""task6c.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z0f3t3l_eUmPxIdxhciUEhw_KV75CB0R

Find the words with atleast 6 letters
"""

lst=[]
atleast=[]
number=0
with open("/content/about.txt", "r") as rf:
  for line in rf:
    lst.extend(line.split())

  for i in lst:
    if(len(i)>=6):
      atleast.append(i)
  
  number=len(atleast)
print("the words with atleast 6 letters are:")
print(atleast)
print("total numbers of words :",number)

"""Find the most frequently used word"""

lst=[]
with open("/content/about.txt", "r") as rf:
    for line in rf:
        lst.extend(line.split())

from collections import Counter

counts = Counter(lst)
max_key=max(counts, key=counts.get)
print("the word with maximum frequency is:")
print(max_key)