# -*- coding: utf-8 -*-
"""task6b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wYbBW4V_G3vDk-OF_XTH4e9v6cIco-XQ
"""

import pandas as pd
 
df = pd.read_csv("/content/Q2-Dataset.csv")
print(df)

df['LotFrontage'] = df['LotFrontage'].fillna(0)
print(df)

df['Alley'] = df['Alley'].fillna("No")
print(df)

df.replace(to_replace ="NAmes",value ="Names")
print(df)

df[['BsmtQual','BsmtCond']] = df[['BsmtQual','BsmtCond']].fillna("No")
print(df[['BsmtQual','BsmtCond']])

df['BsmtExposure'] = df['BsmtExposure'].fillna("NoExposure")
print(df['BsmtExposure'])

df[['BsmtFinType1','BsmtFinType2']] = df[['BsmtFinType1','BsmtFinType2']].fillna("NotPresent")
print(df[['BsmtFinType1','BsmtFinType2']])

#final dataset 
print(df)